org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=true           # Disable Gradle daemon (saves RAM)
org.gradle.parallel=true         # Disable parallel builds (reduces CPU/RAM spikes)
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true